### ISSUE TITLE
"Vanilla" definition shall be fixed on filters

### ISSUE THREAD

**Issue by arkantoster** [5etools-mirror-1/5etools-mirror-1.github.io#50]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
Bug

Issue:
The current definition of vanilla is outdated.

Page(s) affected:
All pages with filters

Reproduction steps:
On filter modal, choose the "three dots" on source section(the first one),  then choose 'Select "Vanilla" Sources'

Additional information:
Idk if I could just commit a change on a branch and ask for a merge.

Browser (Chromium, Firefox, Edge, etc):
Any

Platform (Windows, iOS, Android, etc):
Any

**Comment by TheGiddyLimit** [comment]
Define "outdated;" what would you like to see changed?

> Idk if I could just commit a change on a branch and ask for a merge.

Go for it!

**Comment by arkantoster** [comment]
> Define "outdated;" what would you like to see changed?

I'll use the filter on the races pages for the following example.
When I choose the 'Select "Vanilla" Sources' option, the following books are selected: 

- DMG
- FTD
- MPMM
- MTF
- PHB
- SCAG
- TCE
- VGM
- TTP

But, according to [DnD Beyond](https://www.dndbeyond.com/legacy), MTF and VGM has become a legacy content since the launch of MPMM. Besides that, I couldn't understand why "The Tortle Package" is vanilla, but "One Grung Above" isn't.

> Go for it!

Nice, I'll do it.

**Comment by TheGiddyLimit** [comment]
> MTF and VGM has become a legacy content since the launch of MPMM

Fair point. TTP is also redundant, then. Traditionally, it was included because the AL Player's Guide considered it an honorary part of XGE. OGA never received such treatment (and still doesn't, according to the [latest AL Player's Guide](https://media.wizards.com/2022/dnd/downloads/DDAL_PlayersGuidev12_1.pdf), hence the difference there.

Interestingly, the Player's Guide version also says Locathah Rising is available as a source of player options, which I wasn't aware of. Unfortunately it also includes some junky adventure-specific creatures in 5etools, so it won't be making the list.

Since you've yet to make the PR, I'll go ahead and scrub it up for next release. Consider it done.

**Comment by gitscosh** [comment]
I would like the "vanilla" selection to remain as it is for my own fork. Which files will be affected so I can be sure to selectively merge from upstream?

**Comment by TheGiddyLimit** [comment]
`js/parser.js` is the only file affected:

```patch
diff --git a/js/parser.js b/js/parser.js
--- a/js/parser.js	(revision f7681fe5be684c202f5f4580f8681d2957ce1789)
+++ b/js/parser.js	(revision 891bee8fb2d50297051e993c90bbd778aa999cd3)
@@ -3212,10 +3212,10 @@
 	SRC_MM,
 	SRC_PHB,
 	SRC_SCAG,
-	// SRC_TTP, // "Legacy" source, removed in favor of MPMM
-	// SRC_VGM, // "Legacy" source, removed in favor of MPMM
+	SRC_TTP,
+	SRC_VGM,
 	SRC_XGE,
-	// SRC_MTF, // "Legacy" source, removed in favor of MPMM
+	SRC_MTF,
 	SRC_SAC,
 	SRC_MFF,
 	SRC_SADS,
```

**Comment by gitscosh** [comment]
Thank you!
